# API keys and settings
API_KEY = 'your_api_key'
API_SECRET = 'your_api_secret'
SYMBOL = 'BTC/USDT'
TIMEFRAME = '1h'
LIMIT = 200
RISK_PERCENTAGE = 0.05
TRADE_AMOUNT = 0.01
STOP_LOSS_PERCENTAGE = 0.02
TAKE_PROFIT_PERCENTAGE = 0.05
